package game;

/**
 *
 * @author jrlytle
 */
public class CharacterDescriptions
{
    public String getCharacterDescription(int charID, int choice)
    {
        String descriptionOne = "";
        String descriptionTwo = "";
        switch (charID)
        {
            case 1: descriptionOne = "Son of Duke Vylon, and successor of";
                descriptionTwo = " the Tilfing.";
                break;
            case 2: descriptionOne = "Knight of Chalphy. A calm and serious ";
                descriptionTwo = "character, with a strong sense of honor.";
                break;
            case 3: descriptionOne = "Knight of Chalphy. The polar opposite of";
                descriptionTwo = "Noish, and a bit of a womaniser.";
                break;
            case 4: descriptionOne = "Knight of Chalphy. Has the three essential elements";
                descriptionTwo = "of an Armor Knight: Stubborn, strong and slow.";
                break;
            case 5: descriptionOne = "Extremely charismatic and can";
                descriptionTwo = "bond with almost everybody.";
                break;
            case 6: descriptionOne = "Knight of Jungby. He was injured whilst trying";
                descriptionTwo = "to protect Adean from the Verdane bandits.";
                break; //Need to adjust
            case 7: descriptionOne = "Younger half-brother of Velthomer's Duke Alvis.";
                descriptionTwo = "He joins Sigurd's army to rescue Adean.";
                break;
            case 8: descriptionOne = "Son of Dozel's Duke Langobalt.";
                descriptionTwo = "A cool character, and Azel's best friend.";
                break;
            case 9: descriptionOne = "Prince of Lenster; successor of the Gaeborg.";
                descriptionTwo = "He is Sigurd's best friend and Ethlin's husband.";
                break;
            case 10: descriptionOne = "Cuan's wife and Sigurd's younger sister.";
                descriptionTwo = "She persuades Cuan to aid her brother's cause.";
                break;
            case 11: descriptionOne = "A trainee knight of Lenster,";
                descriptionTwo = "and a loyal subordinate of Prince Cuan.";
                break; //Gen 2: Knight of Lenster who once served Prince Cuan. A truly loyal and noble man.
            case 12: descriptionOne = "Thief from Verdane. He was imprisoned in";
                descriptionTwo = "Marpha Castle, but was released by Prince Jamka.";
                break;
            case 13: descriptionOne = "Daughter of Jungby's Duke Ring. She joins";
                descriptionTwo = "Sigurd's army to search for her long-lost sister.";
                break;
            case 14: descriptionOne = "Princess of Isaac, and Mariccle's younger sister.";
                descriptionTwo = "She is forced to fight when Shanan is captured.";
                break;
            case 15: descriptionOne = "A mysterious young girl who resides in the spirit";
                descriptionTwo = "forest. She and Sigurd fall in love at first sight.";
                break;
            case 16: descriptionOne = "Prince of Verdane. He wants to stop";
                descriptionTwo = "Verdane from warring with Grandbell.";
                break;
            case 17: descriptionOne = "An arena combatant who has";
                descriptionTwo = "connections to the Kingdom of Isaac.";
                break;
            case 18: descriptionOne = "Princess of Nodion, and Eltshan's younger";
                descriptionTwo = "half-sister. Admired by both civilians and nobles.";
                break;
            case 19: descriptionOne = "A mercenary who is wary of his master's";
                descriptionTwo = "intentions. Apparently an old friend of King Eltshan.";
                break;
            case 20: descriptionOne = "Prince of Silesia, and the successor of the";
                descriptionTwo = "Holsety tome. He masquerades as a traveling bard.";
                break;
            case 21: descriptionOne = "A travelling dancer, who dances to aid";
                descriptionTwo = "the war-suffering civilians. She follows Levin.";
                break;
            case 22: descriptionOne = "A pegasus knight of Silesia. She is";
                descriptionTwo = "ordered to search for the missing Prince Levin.";
                break;
            case 23: descriptionOne = "Daughter of Freege's Duke Reptor.";
                descriptionTwo = "She admires Father Claude.";
                break;
            case 24: descriptionOne = "Ruler of Edda; successor of the Valkyrie staff.";
                descriptionTwo = "He travels to Blaggi Tower to discover the truth.";
                break;
            case 25: descriptionOne = "Leader of the Orgahill pirates, who was raised";
                descriptionTwo = "by the original leader. She is Adean's twin sister.";
                break;
            case 26: descriptionOne = "Son of Sigurd and Diadora; known as the";
                descriptionTwo = "\"Prince of Light\". Leader of the Liberation Army.";
                break;
            case 27: descriptionOne = "Daughter of Jungby's Lady Adean.";
                descriptionTwo = "A kind-hearted cleric like her mother.";
                break;
            case 28: descriptionOne = "A young girl from the streets of Isaac. Hides her";
                descriptionTwo = "feelings for Celice due to their class difference.";
                break;
            case 29: descriptionOne = "Lakche's twin brother. He has a deep respect";
                descriptionTwo = "for his cousin, Prince Shanan.";
                break;
            case 30: descriptionOne = "Radney's twin brother. One of the initial";
                descriptionTwo = "members of the Liberation Army.";
                break;
            case 31: descriptionOne = "Daughter of Isaac's Princess Ira.";
                descriptionTwo = "She inherited her mother's iron will.";
                break;
            case 32: descriptionOne = "A female swordfighter. Hates men with a";
                descriptionTwo = "passion, except her saviour, Shanan.";
                break;
            case 33: descriptionOne = "A key member of the Liberation Army.";
                descriptionTwo = "He passed on his martial arts and wisdom to Celice.";
                break;
            case 34: descriptionOne = "Son of Nodion's Princess Lachesis.";
                descriptionTwo = "A charismatic youth who inherited his mother's grace.";
                break;
            case 35: descriptionOne = "Son of one of Eltshan's Cross Knights.";
                descriptionTwo = "After his parents died, he escaped to Isaac.";
                break;
            case 36: descriptionOne = "Son of Jungby's Lady Adean. A kind youth";
                descriptionTwo = "who possesses a strong sense of justice.";
                break;
            case 37: descriptionOne = "Arch Knight from Isaac. A kind-hearted";
                descriptionTwo = "male who looks out for his little sister.";
                break;
            case 38: descriptionOne = "An amnesiac young girl who was rescued";
                descriptionTwo = "by Levin. Carrier of the Heim bloodline.";
                break;
            case 39: descriptionOne = "Daughter of Fury; a Pegasus Knight like";
                descriptionTwo = "her mother. Travelling in search of her brother.";
                break;
            case 40: descriptionOne = "A Pegasus Knight from Silesia who";
                descriptionTwo = "is searching for her brother.";
                break;
            case 41: descriptionOne = "Son of Freege's Lady Tiltyu. He leaves on a";
                descriptionTwo = "journey after hearing news of his long-lost sister.";
                break;
            case 42: descriptionOne = "Son of Freege's Lady Ethnia. He joins";
                descriptionTwo = "the Liberation Army to bring back his sister.";
                break;
            case 43: descriptionOne = "Son of Dozel's Duke Danan. He and Johalva";
                descriptionTwo = "vie for the affection of ";
                /*if(inh.getHusband(14) == 0)
      {
        descriptionTwo += "Radney.";
      }
      else
      {
        descriptionTwo += "Lakche.";
      }*/
                break;
            case 44: descriptionOne = "Johan's younger brother. He acts like";
                descriptionTwo = "a bad guy, but is honorable deep inside.";
                break;
            case 45: descriptionOne = "Prince of Isaac; successor of the Balmunk.";
                descriptionTwo = "He formed the Liberation Army to topple Grandbell.";
                break;
            case 46: descriptionOne = "Daughter of Briggid. A honorable thief who";
                descriptionTwo = "maintains an orphanage for war-torn children.";
                break;
            case 47: descriptionOne = "Orphan from Conote. A girl thief";
                descriptionTwo = "who steals to fund an orphanage.";
                break;
            case 48: descriptionOne = "Prince of Lenster; Cuan and Ethlin's son.";
                descriptionTwo = "After reclaiming his homeland, he faces a new danger.";
                break;
            case 49: descriptionOne = "Delmud's younger sister. She was raised";
                descriptionTwo = "by Fin and fought alongside Leaf's forces.";
                break;
            case 50: descriptionOne = "Tristan's younger sister. Raised by Fin after";
                descriptionTwo = "her adopted father was murdered by the Empire.";
                break;
            case 51: descriptionOne = "Son of Nodion's King Eltshan; successor of";
                descriptionTwo = "the Mistoltin. He was raised as a mercenary.";
                break;
            case 52: descriptionOne = "Daughter of Sylvia. She was raised at";
                descriptionTwo = "Darna and earns a living as a dancer.";
                break;
            case 53: descriptionOne = "A prideful and beautiful dancer.";
                descriptionTwo = "She is confined by Darna's Lord Bramsel.";
                break;
            case 54: descriptionOne = "Arthur's younger sister. She was taken in by";
                descriptionTwo = "her uncle, Blume, when she was younger.";
                break;
            case 55: descriptionOne = "Amid's younger sister. She was taken to Alster";
                descriptionTwo = "by her uncle, Blume, and joined the Freege army.";
                break;
            case 56: descriptionOne = "Patty's older brother; successor of the Ichival.";
                descriptionTwo = "Works as a mercenary to help orphans.";
                break;
            case 57: descriptionOne = "Daisy's older brother, known as the \"Hitman of Conote\".";
                descriptionTwo = "A kind youth who fights to aid orphans.";
                break;
            case 58: descriptionOne = "Fee's older brother. He left in search of his";
                descriptionTwo = "missing father and ended up defending Manster.";
                break;
            case 59: descriptionOne = "Femina's older brother. A sage from Silesia";
                descriptionTwo = "who is travelling in search of his missing father.";
                break;
            case 60: descriptionOne = "General of Thracia, known as the \"Shield of Thracia\".";
                descriptionTwo = "Forced to fight against his own will.";
                break;
            case 61: descriptionOne = "Leen's younger brother; Hannibal's adopted son.";
                descriptionTwo = "He was taken hostage to make Hannibal fight.";
                break;
            case 62: descriptionOne = "Laylea's younger brother; Hannibal's adopted son.";
                descriptionTwo = "He was taken hostage to control Hannibal.";
                break;
            case 63: descriptionOne = "Cuan and Ethlin's daughter; successor of";
                descriptionTwo = "the Gaeborg. She was raised by Trabant.";
                break;
            case 64: break;
            case 65: break;
            case 66: break;
            case 67: descriptionOne = "Ruler of Velthomer, and successor of the";
                descriptionTwo = "Falaflame tome. He serves Grandbell's King Azmure.";
                break; //Gen 2: The first emperor of Grandbell. His shattered dreams of peace and equality cause him distress.
            case 68: descriptionOne = "King of Nodion; successor of the Mistoltin.";
                descriptionTwo = "He studied at military school with Sigurd and Cuan.";
                break;
            case 69: break;
            case 70: break;
            case 71: break;
            case 72: break;
            case 73: break;
            case 74: break;
            case 75: break;
            case 76: break;
            case 77: break;
            case 78: break;
            case 79: break;
            case 80: break;
            case 81: break;
            case 82: break;
            case 83: break;
            case 84: break;
            case 85: break;
            case 86: break;
            case 87: break;
            case 88: break;
            case 89: break;
            case 90: break;
            case 91: break;
            case 92: break;
            case 93: break;
            case 94: break;
            case 95: break;
            case 96: break;
            case 97: break;
            case 98: break;
            case 99: break;
            case 100: break;
            case 101: break;
            case 102: break;
            case 103: break;
            case 104: break;
            case 105: break;
            case 106: break;
            case 107: break;
            case 108: break;
            case 109: break;
            case 110: break;
            case 111: break;
            case 112: break;
            case 113: break;
            case 114: break;
            case 115: break;
            case 116: break;
            case 117: break;
            case 118: break;
            case 119: break;
            case 120: break;
            case 121: break;
            case 122: break;
            case 123: break;
            case 124: break;
            case 125: break;
            case 126: break;
            case 127: break;
            case 128: break;
            case 129: break;
            case 130: descriptionOne = "Alvis and Diadora's son; the imperial prince";
                descriptionTwo = "of Grandbell. Vessel of the dark god Loputousu.";
                break;
            case 131: break;
            case 132: break;
            case 133: break;
            case 134: break;
            case 135: break;
            case 136: break;
            case 137: break;
            case 138: break;
            case 139: break;
            case 140: break;
            case 141: break;
            case 142: break;
            case 143: break;
            case 144: break;
            case 145: break;
            case 146: break;
            case 147: break;
            case 148: break;
            case 149: break;
            case 150: break;
            case 151: break;
            case 152: break;
            case 153: break;
            case 154: break;
            case 155: break;
            case 156: break;
            case 157: descriptionOne = "Eltshan's wife, and Aless's mother.";
                descriptionTwo = "She was originally a noble from Lenster.";
                break;
            //GENERIC CHARACTERS
        }
        if (choice == 0)
        {
            return descriptionOne;
        }
        else
        {
            return descriptionTwo;
        }
    }
}
