package game;

/**
 *
 * @author jrlytle
 */
public class SkillTips
{
  int rectLength = 0;
  int heightModifier = 1;
  public String getSkillTips(int skill, int choice)
  {
    String descriptionOne = "";
    String descriptionTwo = "";
    String descriptionThree = "";
    switch(skill)
    {
        default:  descriptionOne = "";
                  descriptionTwo = "";
                  break;
        case 0:   descriptionOne = "Big Shield: Take no damage from one of the";
                  descriptionTwo = "enemy's attacks. Activation = (User's Level)%";
                  break;
        case 1:   descriptionOne = "Wrath: Always critical when HP";
                  descriptionTwo = "is below [(Max HP/2) + 1]";
                  break;
        case 2:   descriptionOne = "Pursuit: Always double attack when";
                  descriptionTwo = "user's Attack Speed > enemy's Attack Speed";
                  break;
        case 3:   descriptionOne = "Continue: Allows a consecutive attack";
                  descriptionTwo = "Activation = (Attack Speed +20)%";
                  break;
        case 4:   descriptionOne = "Steal: On a successful hit, user";
                  descriptionTwo = "takes all of the enemy's gold";
                  break;
        case 5:   descriptionOne = "Awareness: Negates enemy critical attacks,";
                  descriptionTwo = "sword skills and effective bonus towards user";
                  break;
        case 6:   descriptionOne = "Critical: Allows user to perform critical attacks";
                  descriptionTwo = "with critical rate = (skill + weapons kill bonus)%";
                  break;
        case 7:   descriptionOne = "Ambush: Always attack first when HP is";
                  descriptionTwo = "below Max HP/2, negates enemy's Charge";
                  break;
        case 8:   descriptionOne = "Charge: Activates 2~20 rounds of combat when";
                  descriptionTwo = "HP is above or equal to 25";
                  descriptionThree = "Activation = [User's AS - Enemy's AS + (HP/2)]%";
                  break;
        case 9:   descriptionOne = "Dance: Allows all adjacent units,";
                  descriptionTwo = "who have already moved, to move again";
                  break;
        case 10:  descriptionOne = "Charisma: All units within a 3 tile radius";
                  descriptionTwo = "receive a 10% support bonus";
                  descriptionThree = "(to accuracy and avoid) from the user";
                  break;
        case 11:  descriptionOne = "Prayer: When user's HP is under or equal to 10,";
                  descriptionTwo = "increases avoid by [(11 - HP) x 10] for one turn";
                  break;
        case 12:  descriptionOne = "Life: User recovers 5~10 HP during";
                  descriptionTwo = "the beginning of each turn";
                  break;
        case 13:  descriptionOne = "Elite: User receives double EXP";
                  descriptionTwo = "(maximum at one time is 100)";
                  break;
        case 14:  descriptionOne = "Bargain: User can buy items or";
                  descriptionTwo = "repair items for half price";
                  break;
        case 15:  descriptionOne = "Astra: Activates 5 continuous attacks";
                  descriptionTwo = "(10 with a Hero weapon), can not activate Continue or";
                  descriptionThree = "another sword skill simultaneously. Activation = (Skill/2)%";
                  break;
        case 16:  descriptionOne = "Luna: Halves enemy's defenses, can not activate another ";
                  descriptionTwo = "sword skill simultaneously. Activation = Skill%";
                  break;
        case 17:  descriptionOne = "Sol: Restores HP equal to half of damage done";
                  descriptionTwo = "to enemy, can not activate another sword skill";
                  descriptionThree = "simultaneously. Activation = Skill%";
                  break;
        case 18:  descriptionOne = "Holy Sword: Increases damage by 20, also may reduce";
                  descriptionTwo = "damage taken by 20. Activation = (Skill/4)%";
                  break;
        case 19:  descriptionOne = "Darkness Sword: Multiplies damage by 1, 2 or 3, also may";
                  descriptionTwo = "reduce damage taken by 20. Activation: (Skill/4)%";
                  break;
        case 20:  descriptionOne = "Return: Allows user to";
                  descriptionTwo = "return to the main castle";
                  break;
        case 21:  descriptionOne = "Recover: User recovers all HP during";
                  descriptionTwo = "the beginning of each turn";
                  break;
        case 22:  descriptionOne = "Re-move: Allows user to use up leftover";
                  descriptionTwo = "movement after performing an action";
                  break;
        case 23:  descriptionOne = "Dual Strike+: Adds 10%";
                  descriptionTwo = "to the Dual Strike rate";
                  break;
        case 24:  descriptionOne = "Charm: Hit rate and Avoid +5 to";
                  descriptionTwo = "all allies within a 3 tile radius";
                  break;
        case 25:  descriptionOne = "Aether: Attack twice consecutively, with the";
                  descriptionTwo = "first strike having a Sol effect and the second";
                  descriptionThree = "strike having a Luna effect. Activation: (Skill/2)%";
                  break;
        case 26:  descriptionOne = "Rightful King: Adds 10% to";
                  descriptionTwo = "Skill activation rates";
                  break;
        case 27:  descriptionOne = "Veteran: Experience gain x 1.5";
                  descriptionTwo = "when paired up";
                  break;
        case 28:  descriptionOne = "Solidarity: Critical and";
                  descriptionTwo = "Critical Avoid +10 to adjacent allies";
                  break;
        case 29:  descriptionOne = "Ignis: Adds (Magic)/2 to Strength when";
                  descriptionTwo = "dealing physical damage and (Strength)/2 to";
                  descriptionThree = "Magic when dealing magical damage";
                  break;
        case 30:  descriptionOne = "Rally Spectrum: All Stats +4 to all allies";
                  descriptionTwo = "within a 3 tile radius for one Turn when the";
                  descriptionThree = "Rally command is used";
                  break;
        case 31:  descriptionOne = "Discipline: Weapon experience x2";
                  break;
        case 32:  descriptionOne = "Outdoor Fighter: Hit rate and";
                  descriptionTwo = "Avoid +10 when fighting outdoors";
                  break;
        case 33:  descriptionOne = "Defender: All Stats +1 when paired up";
                  break;
        case 34:  descriptionOne = "Aegis: Halves damage from bows,";
                  descriptionTwo = "tomes and dragonstones";
                  break;
        case 35:  descriptionOne = "Dual Guard+: Adds 10% to the Dual Guard rate";
                  break;
        case 36:  descriptionOne = "Defense + 2";
                  break;
        case 37:  descriptionOne = "Indoor Fighter: Hit rate and";
                  descriptionTwo = "Avoid +10 when fighting indoors";
                  break;
        case 38:  descriptionOne = "Rally Defense: Defence +4 to all allies";
                  descriptionTwo = "within a 3 tile radius for one Turn when the";
                  descriptionThree = "Rally command is used";
                  break;
        case 39:  descriptionOne = "Pavise: Halves damage from swords, lances, axes";
                  descriptionTwo = "(includes magical variants) and beaststones";
                  break;
        case 40:  descriptionOne = "Avoid + 10";
                  break;
        case 41:  descriptionOne = "Swordfaire: Strength +5 when equipped with a sword";
                  descriptionTwo = "(Magic +5 when equipped with a Magic Sword)";
                  break;
        case 42:  descriptionOne = "Armsthrift: Attack does not reduce weapon usage";
                  descriptionTwo = "Activation = (Luck*2)%";
                  break;
        case 43:  descriptionOne = "Patience: Hit rate and Avoid +10";
                  descriptionTwo = "during the enemy’s Turn";
                  break;
        case 44:  descriptionOne = "Axebreaker: Hit rate and Avoid +50";
                  descriptionTwo = "when the enemy is equipped with an axe";
                  break;
        case 45:  descriptionOne = "HP + 5";
                  break;
        case 46:  descriptionOne = "Zeal: Critical +5";
                  break;
        case 47:  descriptionOne = "Rally Strength: Strength +4 to all allies";
                  descriptionTwo = "within a 3 tile radius for one Turn when the";
                  descriptionThree = "Rally command is used";
                  break;
        case 48:  descriptionOne = "Counter: Returns damage when attacked by an";
                  descriptionTwo = "adjacent enemy (except damage that KOs the user)";
                  break;
        case 49:  descriptionOne = "Despoil: Obtain Bullion (S) from the enemy if";
                  descriptionTwo = "the user defeats the enemy. Activation: Luck%";
                  break;
        case 50:  descriptionOne = "Gamble: Hit rate -5, Critical +10";
                  break;
        case 51:  descriptionOne = "Axefaire: Strength +5 when equipped with an axe";
                  descriptionTwo = "(Magic +5 when equipped with a Magic Axe)";
                  break;
        case 52:  descriptionOne = "Skill + 2";
                  break;
        case 53:  descriptionOne = "Prescience: Hit rate and Avoid +15";
                  descriptionTwo = "during the user’s Turn";
                  break;
        case 54:  descriptionOne = "Hit Rate + 20";
                  break;
        case 55:  descriptionOne = "Bowfaire: Strength +5 when";
                  descriptionTwo = "equipped with a bow";
                  break;
        case 56:  descriptionOne = "Rally Skill: Skill +4 to all allies within a";
                  descriptionTwo = "3 tile radius for one Turn when the Rally";
                  descriptionThree = "command is used";
                  break;
        case 57:  descriptionOne = "Bowbreaker: Hit rate and Avoid +50";
                  descriptionTwo = "when the enemy is equipped with a bow";
                  break;
        case 58:  descriptionOne = "Locktouch: Open doors and chests";
                  descriptionTwo = "without the need of keys";
                  break;
        case 59:  descriptionOne = "Movement + 1";
                  break;
        case 60:  descriptionOne = "Lethality: Instantly defeats the enemy";
                  descriptionTwo = "Activation (Skill/4)%";
                  break;
        case 61:  descriptionOne = "Pass: User can pass through";
                  descriptionTwo = "tiles occupied by enemy units";
                  break;
        case 62:  descriptionOne = "Lucky Seven: Hit rate and Avoid +20";
                  descriptionTwo = "up to the 7th Turn";
                  break;
        case 63:  descriptionOne = "Acrobat: All traversable terrain";
                  descriptionTwo = "costs 1 movement point to cross";
                  break;
        case 64:  descriptionOne = "Speed + 2";
                  break;
        case 65:  descriptionOne = "Relief: Recover 20% HP at the start of the user’s";
                  descriptionTwo = "Turn if no units are within a 3 tile radius";
                  break;
        case 66:  descriptionOne = "Rally Speed: Speed +4 to all allies within a";
                  descriptionTwo = "3 tile radius for one Turn when the Rally";
                  descriptionThree = "command is used";
                  break;
        case 67:  descriptionOne = "Lancefaire: Strength +5 when equipped with a lance";
                  descriptionTwo = "(Magic +5 when equipped with a Magic Lance)";
                  break;
        case 68:  descriptionOne = "Rally Movement: Movement +1 to all allies";
                  descriptionTwo = "within a 3 tile radius for one Turn when the";
                  descriptionThree = "Rally command is used";
                  break;
        case 69:  descriptionOne = "Galeforce: Allows the user another full";
                  descriptionTwo = "action after they defeat an enemy during the";
                  descriptionThree = "user’s Turn (only once per Turn)";
                  break;
        case 70:  descriptionOne = "Strength + 2";
                  break;
        case 71:  descriptionOne = "Tantivy: Hit rate and Avoid +10 if";
                  descriptionTwo = "no allies within a 3 tile radius";
                  break;
        case 72:  descriptionOne = "Quick Burn: Hit rate and Avoid +15 at the";
                  descriptionTwo = "start of the chapter. Effect decreases with";
                  descriptionThree = "each passing Turn";
                  break;
        case 73:  descriptionOne = "Swordbreaker: Hit rate and Avoid +50";
                  descriptionTwo = "when the enemy is equipped with a sword";
                  break;
        case 74:  descriptionOne = "Deliverer: Movement +2";
                  descriptionTwo = "when paired up";
                  break;
        case 75:  descriptionOne = "Lancebreaker: Hit rate and Avoid +50";
                  descriptionTwo = "when the enemy is equipped with a lance";
                  break;
        case 76:  descriptionOne = "Magic + 2";
                  break;
        case 77:  descriptionOne = "Focus: Critical +10 when no";
                  descriptionTwo = "allies within a 3 tile radius";
                  break;
        case 78:  descriptionOne = "Rally Magic: Magic +4 to all allies within a";
                  descriptionTwo = "3 tile radius for one Turn when the Rally";
                  descriptionThree = "command is used";
                  break;
        case 79:  descriptionOne = "Tomefaire: Magic +5 when";
                  descriptionTwo = "equipped with a Tome";
                  break;
        case 80:  descriptionOne = "Hex: Avoid -15 to all";
                  descriptionTwo = "adjacent enemies";
                  break;
        case 81:  descriptionOne = "Anathema: Avoid and Critical Avoid -10";
                  descriptionTwo = "to all enemies within a 3 tile radius";
                  break;
        case 82:  descriptionOne = "Vengeance: Deals (user’s Max HP – Current HP)/2";
                  descriptionTwo = "extra damage, Activation = (Skill*2)%";
                  break;
        case 83:  descriptionOne = "Tomebreaker: Hit rate and Avoid +50";
                  descriptionTwo = "when the enemy is equipped with a tome";
                  break;
        case 84:  descriptionOne = "Slow Burn: Hit rate and Avoid increases";
                  descriptionTwo = "by 1 each Turn, up to the 15th Turn";
                  break;
        case 85:  descriptionOne = "Lifetaker: User recovers 50% HP after they";
                  descriptionTwo = "defeat an enemy during the user’s Turn";
                  break;
        case 86:  descriptionOne = "Miracle: Character survives with 1 HP after";
                  descriptionTwo = "receiving an attack that would otherwise KO";
                  descriptionThree = "them (must have over 1 HP). Activation = Luck%";
                  break;
        case 87:  descriptionOne = "Healtouch: Restores an extra";
                  descriptionTwo = "5 HP when healing allies";
                  break;
        case 88:  descriptionOne = "Rally Luck: Luck +8 to all allies within a 3 tile";
                  descriptionTwo = "radius for one Turn when the Rally command is used";
                  break;
        case 89:  descriptionOne = "Renewal: Recover 30% HP at the";
                  descriptionTwo = "start of the user’s Turn";
                  break;
        case 90:  descriptionOne = "Resistance + 2";
                  break;
        case 91:  descriptionOne = "Demoiselle: Avoid and Critical Avoid +10";
                  descriptionTwo = "to all male allies within a 3 tile radius";
                  break;
        case 92:  descriptionOne = "Rally Resistance: Resistance +4 to all allies";
                  descriptionTwo = "within a 3 tile radius for one Turn when the";
                  descriptionThree = "Rally command is used";
                  break;
        case 93:  descriptionOne = "Dual Support+: Increases the";
                  descriptionTwo = "support bonus effect";
                  break;
        case 94:  descriptionOne = "Aptitude: Adds 20% to all growth";
                  descriptionTwo = "rates during Level Ups";
                  break;
        case 95:  descriptionOne = "Underdog: Hit rate and Avoid +15 when user’s";
                  descriptionTwo = "Level is lower than the enemy (promoted units";
                  descriptionThree = "count as Level +20)";
                  break;
        case 96:  descriptionOne = "Luck + 4";
                  break;
        case 97:  descriptionOne = "Special Dance: Strength, Magic, Defence and";
                  descriptionTwo = "Resistance +2 for one Turn for the unit(s)";
                  descriptionThree = "who receives the user’s Dance";
                  break;
        case 98:  descriptionOne = "Even Rhythm: Hit rate and Avoid +10";
                  descriptionTwo = "during even numbered Turns";
                  break;
        case 99:  descriptionOne = "Beastbane: Deals effective damage to";
                  descriptionTwo = "beast units when user is a Taguel";
                  break;
        case 100: descriptionOne = "Odd Rhythm: Hit rate and Avoid +10 ";
                  descriptionTwo = "during odd numbered Turns";
                  break;
        case 101: descriptionOne = "Wyrmsbane: Deals effective damage to";
                  descriptionTwo = "dragon units when user is a Manakete";
                  break;
        case 102: descriptionOne = "Shadowgift: Enables usage of";
                  descriptionTwo = "Dark Tomes for Tome wielders";
                  break;
        case 103: descriptionOne = "Conquest: Negates user’s Beast";
                  descriptionTwo = "and Armor type weaknesses";
                  break;
        case 104: descriptionOne = "Resistance +10";
                  break;
        case 105: descriptionOne = "Aggressor: Attack +10 during ";
                  descriptionTwo = "the user’s Turn";
                  break;
        case 106: descriptionOne = "Rally Heart: All stats +2 and Movement +1 to";
                  descriptionTwo = "all allies within a 3 tile radius for one";
                  descriptionThree = "Turn when the Rally command is used";
                  break;
        case 107: descriptionOne = "Bond: Restores 10 HP to all allies within a 3 tile";
                  descriptionTwo = "radius at the beginning of the user’s Turn";
                  break;
        case 108: descriptionOne = "All Stats + 2: Strength, Magic, Skill,";
                  descriptionTwo = "Speed, Luck, Defence and Resistance +2";
                  break;
        case 109: descriptionOne = "Paragon: Experience gain x2";
                  break;
        case 110: descriptionOne = "Iote's Shield: Negates user’s";
                  descriptionTwo = "Flying type weakness";
                  break;
        case 111: descriptionOne = "Limit Breaker: Raises the character’s";
                  descriptionTwo = "maximum stats by 10";
                  break;
        case 112: descriptionOne = "Dragonskin: Halves damage, negates";
                  descriptionTwo = "Counter and Lethality";
                  break;
        case 113: descriptionOne = "Hit Rate +10";
                  break;
        case 114: descriptionOne = "Rightful God: Adds 30% to";
                  descriptionTwo = "Skill activation rates";
                  break;
        case 115: descriptionOne = "Ambush+: Always attack first";
                  descriptionTwo = "during the enemy’s Turn";
                  break;
        case 116: descriptionOne = "Luna+: Every attack halves";
                  descriptionTwo = "enemy's defense";
                  break;
        case 117: descriptionOne = "Hawkeye: Attacks always";
                  descriptionTwo = "strike the enemy";
                  break;
        case 118: descriptionOne = "Pavise+: Halves damage from swords, lances, axes";
                  descriptionTwo = "(includes magical variants) and beaststones";
                  break;
        case 119: descriptionOne = "Aegis+: Halves damage from";
                  descriptionTwo = "bows, tomes and dragonstones";
                  break;
    }
    if(choice == 0)
    {
      return descriptionOne;
    }
    if(choice == 1)
    {
      return descriptionTwo;
    }
    return descriptionThree;
  }
}
