package game;

/**
 *
 * @author jrlytle
 */
public class WeaponName
{
    public String getWeaponName(int iD)
    {
        switch (iD)
        {
            //SWORDS - 1
            case 1: return "Bronze Sword";
            case 2: return "Iron Sword";
            case 3: return "Steel Sword";
            case 4: return "Silver Sword";
            case 5: return "Iron Blade";
            case 6: return "Steel Blade";
            case 7: return "Silver Blade";
            case 8: return "Prayer Sword";
            case 9: return "Thief Sword";
            case 10: return "Barrier Sword";
            case 11: return "Berserk Sword";
            case 12: return "Hero Sword";
            case 13: return "Killing Edge";
            case 14: return "Sol";
            case 15: return "Amatsu";
            case 16: return "Sol Katti";
            case 17: return "Silence Sword";
            case 18: return "Sleep Sword";
            case 19: return "Slim Sword";
            case 20: return "Defender Sword";
            case 21: return "Armorslayer";
            case 22: return "Wingslayer";
            case 23: return "Wyrmslayer";
            case 24: return "Short Sword";
            case 25: return "Poison Sword";
            case 26: return "Elite Sword";
            case 27: return "Long Sword";
            case 28: return "Rapier";
            case 29: return "Noble Rapier";
            case 30: return "King Sword";
            case 31: return "Great Sword";
            case 32: return "Master Sword";
            case 33: return "Darkness Sword";
            case 34: return "Mareeta's Sword";
            case 35: return "Beo Sword";
            case 36: return "Holy Sword";
            case 37: return "Blaggi Sword";
            case 38: return "Loputo Sword";
            case 39: return "Missiletainn";
            case 40: return "Falchion";
            case 41: return "Exalted Falchion";
            case 42: return "Parallel Falchion";
            case 43: return "Mercurius";
            case 44: return "Ragnell";
            case 45: return "Tree Branch";
            case 46: return "Glass Sword";
            case 47: return "Soothing Sword";
            case 48: return "Superior Edge";
            case 49: return "Leaf's Blade";
            case 50: return "Roy's Blade";
            case 51: return "Eliwood's Blade";
            case 52: return "Eirika’s Blade";
            case 53: return "Celice's Blade";
            case 54: return "Alm's Blade";
            case 55: return "Flame Sword";
            case 56: return "Earth Sword";
            case 57: return "Thunder Sword";
            case 58: return "Wind Sword";
            case 59: return "Light Sword";
            case 60: return "Iron Kukri";
            case 61: return "Steel Kukri";
            case 62: return "Silver Kukri";
            case 63: return "Ganglari";
            case 64: return "Siegfried";
            case 65: return "Bottle";
            case 66: return "Umbrella";
            case 67: return "Nohrian Blade";
            case 68: return "Leo’s Iceblade";
            case 69: return "Selena’s Blade";
            case 70: return "Laslow’s Blade";
            case 71: return "True Ganglari";
            case 72: return "Marth’s Spatha";
            case 73: return "Ike’s Backup";
            case 74: return "Lucina’s Estoc";
            case 75: return "Brass Katana";
            case 76: return "Iron Katana";
            case 77: return "Steel Katana";
            case 78: return "Silver Katana";
            case 79: return "Venge Katana";
            case 80: return "Iron Katti";
            case 81: return "Steel Katti";
            case 82: return "Silver Katti";
            case 83: return "Kodachi";
            case 84: return "Wakizashi";
            case 85: return "Axe Splitter";
            case 86: return "Dual Katana";
            case 87: return "Practice Katana";
            case 88: return "Spirit Katana";
            case 89: return "Hagakure Blade";
            case 90: return "Yato";
            case 91: return "Noble Yato";
            case 92: return "Blazing Yato";
            case 93: return "Grim Yato";
            case 94: return "Shadow Yato";
            case 95: return "Alpha Yato";
            case 96: return "Omega Yato";
            case 97: return "Raijinto";
            case 98: return "Daikon Radish";
            case 99: return "Parasol";
            case 100: return "Raider Katana";
            case 101: return "Sunrise Katana";
            case 102: return "Takumi's Shinai";
            case 103: return "Hana's Katana";
            case 104: return "Hinata's Katana";
            case 105: return "Mistoltin";
            case 106: return "Tilfing";
            case 107: return "Balmunk";
            case 108: return "Broken Sword";

            //LANCES - 2
            case 109: return "Bronze Lance";
            case 110: return "Iron Lance";
            case 111: return "Steel Lance";
            case 112: return "Silver Lance";
            case 113: return "Hero Lance";
            case 114: return "Javelin";
            case 115: return "Short Spear";
            case 116: return "Spear";
            case 117: return "Knight Killer";
            case 118: return "Blessed Lance";
            case 119: return "Killer Lance";
            case 120: return "Luna";
            case 121: return "Gradivus";
            case 122: return "Log";
            case 123: return "Glass Lance";
            case 124: return "Miniature Lance";
            case 125: return "Shockstick";
            case 126: return "Superior Lance";
            case 127: return "Fin's Lance";
            case 128: return "Ephraim's Lance";
            case 129: return "Sigurd's Lance";
            case 130: return "Slim Lance";
            case 131: return "Iron Javelin";
            case 132: return "Steel Javelin";
            case 133: return "Silver Javelin";
            case 134: return "Beast Killer";
            case 135: return "Broom";
            case 136: return "Stick";
            case 137: return "Hexlock Spear";
            case 138: return "Xander's Lance";
            case 139: return "Effie's Lance";
            case 140: return "Pieri's Lance";
            case 141: return "Brass Naginata";
            case 142: return "Iron Naginata";
            case 143: return "Steel Naginata";
            case 144: return "Silver Naginata";
            case 145: return "Venge Naginata";
            case 146: return "Iron Nageyari";
            case 147: return "Steel Nageyari";
            case 148: return "Silver Nageyari";
            case 149: return "Swordcatcher";
            case 150: return "Dual Naginata";
            case 151: return "Guard Naginata";
            case 152: return "Bolt Naginata";
            case 153: return "Waterwheel";
            case 154: return "Bamboo Pole";
            case 155: return "Pine Branch";
            case 156: return "Raider Naginata";
            case 157: return "Bold Naginata";
            case 158: return "Hinoka's Spear";
            case 159: return "Subaki's Pike";
            case 160: return "Oboro's Spear";
            case 161: return "Poison Lance";
            case 162: return "Darkness Lance";
            case 163: return "Long Lance";
            case 164: return "Great Lance";
            case 165: return "Master Lance";
            case 166: return "Dragon Lance";
            case 167: return "Gaeborg";
            case 168: return "Gungnir";
            case 169: return "Broken Lance";

            //AXES - 3
            case 170: return "Bronze Axe";
            case 171: return "Iron Axe";
            case 172: return "Steel Axe";
            case 173: return "Silver Axe";
            case 174: return "Hero Axe";
            case 175: return "Hammer";
            case 176: return "Bolt Axe";
            case 177: return "Killer Axe";
            case 178: return "Hand Axe";
            case 179: return "Short Axe";
            case 180: return "Tomahawk";
            case 181: return "Vengeance";
            case 182: return "Wolf Berg";
            case 183: return "Hauteclere";
            case 184: return "Armads";
            case 185: return "Ladle";
            case 186: return "Glass Axe";
            case 187: return "Imposing Axe";
            case 188: return "Volant Axe";
            case 189: return "Superior Axe";
            case 190: return "Orsin's Hatchet";
            case 191: return "Titania's Axe";
            case 192: return "Hector's Axe";
            case 193: return "Iron Star Axe";
            case 194: return "Steel Star Axe";
            case 195: return "Silver Star Axe";
            case 196: return "Aurgelmir";
            case 197: return "Bölverk"; //o with two dots over
            case 198: return "Frying Pan";
            case 199: return "Bone Axe";
            case 200: return "Raider Axe";
            case 201: return "Berserker's Axe";
            case 202: return "Camilla's Axe";
            case 203: return "Arthur's Axe";
            case 204: return "Beruka's Axe";
            case 205: return "Brass Club";
            case 206: return "Iron Club";
            case 207: return "Steel Club";
            case 208: return "Silver Club";
            case 209: return "Venge Club";
            case 210: return "Iron Mace";
            case 211: return "Steel Mace";
            case 212: return "Silver Mace";
            case 213: return "Throwing Club";
            case 214: return "Battering Club";
            case 215: return "Pike-Ruin Club";
            case 216: return "Dual Club";
            case 217: return "Great Club";
            case 218: return "Carp Streamer";
            case 219: return "Hoe";
            case 220: return "Adamant Club";
            case 221: return "Rinkah's Club";
            case 222: return "Ryoma's Club";
            case 223: return "Fuga's Club";
            case 224: return "Poison Axe";
            case 225: return "Devil's Axe";
            case 226: return "Pole Axe";
            case 227: return "Battle Axe";
            case 228: return "Master Axe";
            case 229: return "Pugi";
            case 230: return "Swanchika";
            case 231: return "Broken Axe";

            //BOWS - 4
            case 232: return "Bronze Bow";
            case 233: return "Iron Bow";
            case 234: return "Steel Bow";
            case 235: return "Silver Bow";
            case 236: return "Hero Bow";
            case 237: return "Killer Bow";
            case 238: return "Long Bow";
            case 239: return "Astra";
            case 240: return "Blessed Bow";
            case 241: return "Parthia";
            case 242: return "Yewfelle";
            case 243: return "Nidhogg";
            case 244: return "Double Bow";
            case 245: return "Slack Bow";
            case 246: return "Glass Bow";
            case 247: return "Towering Bow";
            case 248: return "Underdog Bow";
            case 249: return "Superior Bow";
            case 250: return "Wolt's Bow";
            case 251: return "Innes' Bow";
            case 252: return "Crescent Bow";
            case 253: return "Iron Shortbow";
            case 254: return "Steel Shortbow";
            case 255: return "Silver Shortbow";
            case 256: return "Mini Bow";
            case 257: return "Shining Bow";
            case 258: return "Rubber Bow";
            case 259: return "Violin Bow";
            case 260: return "Cupid's Bow";
            case 261: return "Hunter's Bow";
            case 262: return "Anna's Bow";
            case 263: return "Niles' Bow";
            case 264: return "Brass Yumi";
            case 265: return "Iron Yumi";
            case 266: return "Steel Yumi";
            case 267: return "Silver Yumi";
            case 268: return "Spy's Yumi";
            case 269: return "Iron Hankyu";
            case 270: return "Steel Hankyu";
            case 271: return "Silver Hankyu";
            case 272: return "Dual Yumi";
            case 273: return "Illusory Yumi";
            case 274: return "Surefire Yumi";
            case 275: return "Pursuer";
            case 276: return "Fujin Yumi";
            case 277: return "Skadi";
            case 278: return "Bamboo Yumi";
            case 279: return "Harp Yumi";
            case 280: return "Raider Yumi";
            case 281: return "Spellbane Yumi";
            case 282: return "Sidelong Yumi";
            case 283: return "Mikoto's Yumi";
            case 284: return "Setsuna's Yumi";
            case 285: return "Poison Bow";
            case 286: return "Short Bow";
            case 287: return "Great Bow";
            case 288: return "Master Bow";
            case 289: return "Ichival";
            case 290: return "Broken Bow"; //Unusable as a weapon - 15
            case 291: return "Long Arch";
            case 292: return "Iron Arch";
            case 293: return "Killer Arch";
            case 294: return "Great Arch";
            case 295: return "Poison Arch";

            //SHURIKENS/DAGGERS - 5
            case 296: return "Brass Shuriken";
            case 297: return "Iron Shuriken";
            case 298: return "Steel Shuriken";
            case 299: return "Silver Shuriken";
            case 300: return "Spy's Shuriken";
            case 301: return "Dual Shuriken";
            case 302: return "Sting Shuriken";
            case 303: return "Barb Shuriken";
            case 304: return "Flame Shuriken";
            case 305: return "Chakram";
            case 306: return "Chopstick";
            case 307: return "Hair Pin";
            case 308: return "Caltrop";
            case 309: return "Kaze's Needle";
            case 310: return "Saizo's Star";
            case 311: return "Kagero's Dart";
            case 312: return "Bronze Dagger";
            case 313: return "Iron Dagger";
            case 314: return "Steel Dagger";
            case 315: return "Silver Dagger";
            case 316: return "Soldier's Knife";
            case 317: return "Fruit Knife";
            case 318: return "Hunter's Knife";
            case 319: return "Kris Knife";
            case 320: return "Quill Pen";
            case 321: return "Stale Bread";
            case 322: return "Raider Knife";
            case 323: return "Votive Candle";
            case 324: return "Sacrificial Knife";
            case 325: return "Felicia's Plate";
            case 326: return "Jakob's Tray";
            case 327: return "Pebble";
            case 328: return "Broken Shuriken";
            case 329: return "Broken Knife";

            //STAVES - 6
            case 330: return "Live Staff";
            case 331: return "Relive Staff";
            case 332: return "Recover Staff";
            case 333: return "Reblow Staff";
            case 334: return "Reserve Staff";
            case 335: return "Return Staff";
            case 336: return "Warp Staff";
            case 337: return "Rescue Staff";
            case 338: return "Charm Staff";
            case 339: return "Rest Staff";
            case 340: return "Silence Staff";
            case 341: return "Sleep Staff";
            case 342: return "Berserk Staff";
            case 343: return "Thief Staff";
            case 344: return "Goddess Staff";
            case 345: return "Ward";
            case 346: return "Hammerne";
            case 347: return "Kneader";
            case 348: return "Balmwood Staff";
            case 349: return "Catharsis";
            case 350: return "Freeze";
            case 351: return "Enfeeble";
            case 352: return "Entrap";
            case 353: return "Bifröst"; //o with two dots over
            case 354: return "Candy Cane";
            case 355: return "Mushroom Staff";
            case 356: return "Bouquet Staff";
            case 357: return "Elise’s Staff";
            case 358: return "Lilith’s Staff";
            case 359: return "Astral Blessing";
            case 360: return "Bloom Festal";
            case 361: return "Sun Festal";
            case 362: return "Wane Festal";
            case 363: return "Moon Festal";
            case 364: return "Great Festal";
            case 365: return "Hexing Rod";
            case 366: return "Lantern";
            case 367: return "Dumpling Rod";
            case 368: return "Bamboo Branch";
            case 369: return "Sakura’s Rod";
            case 370: return "Purification Rod";
            case 371: return "Torch Staff";
            case 372: return "M Up";
            case 373: return "Rewarp";
            case 374: return "Unlock";
            case 375: return "Kia";
            case 376: return "Valkyrie Staff";
            case 377: return "Broken Staff"; // - 15

            //FIRE - 7
            case 378: return "Fire";
            case 379: return "Elfire";
            case 380: return "Arcfire";
            case 381: return "Bolganone";
            case 382: return "Ember";
            case 383: return "Dying Blaze";
            case 384: return "Micaiah's Pyre";
            case 385: return "Meteor";
            case 386: return "Falaflame";

            //THUNDER - 8
            case 387: return "Thunder";
            case 388: return "Elthunder";
            case 389: return "Thoron";
            case 390: return "Arcthunder";
            case 391: return "Speed Thunder";
            case 392: return "Dime Thunder";
            case 393: return "Superior Jolt";
            case 394: return "Katarina's Bolt";
            case 395: return "Thunderstorm";
            case 396: return "Thorhammer";

            //WIND - 9
            case 397: return "Wind";
            case 398: return "Elwind";
            case 399: return "Tornado";
            case 400: return "Arcwind";
            case 401: return "Rexcalibur";
            case 402: return "Excalibur";
            case 403: return "Wilderwind";
            case 404: return "Celica's Gale";
            case 405: return "Disrobing Gale";
            case 406: return "Grafcalibur";
            case 407: return "Blizzard";
            case 408: return "Holsety";

            //LIGHT - 10
            case 409: return "Lightning";
            case 410: return "Resire";
            case 411: return "Aura";
            case 412: return "Narga";

            //DARK - 11
            case 413: return "Yotsmungand";
            case 414: return "Fenrir";
            case 415: return "Hell";
            case 416: return "Flux";
            case 417: return "Nosferatu";
            case 418: return "Ruin";
            case 419: return "Waste";
            case 420: return "Goetia";
            case 421: return "Grima's Truth";
            case 422: return "Mire";
            case 423: return "Aversa’s Night";
            case 424: return "Poison";
            case 425: return "Stone";
            case 426: return "Loputousu";

            //OTHER MAGIC - CAN BE USED BY ALL MAGIC WIELDERS - 12
            case 427: return "Fimbulvetr";
            case 428: return "Ragnarok";
            case 429: return "Ginnungagap";
            case 430: return "Brynhildr";
            case 431: return "Moonlight";
            case 432: return "Iago’s Tome";
            case 433: return "Odin’s Grimoire";
            case 434: return "Robin’s Primer";
            case 435: return "Rat Spirit";
            case 436: return "Ox Spirit";
            case 437: return "Tiger Spirit";
            case 438: return "Rabbit Spirit";
            case 439: return "Dragon Spirit";
            case 440: return "Calamity Gate";
            case 441: return "Snake Spirit";
            case 442: return "Horse Spirit";
            case 443: return "Sheep Spirit";
            case 444: return "Paper";
            case 445: return "Malevolent Text";
            case 446: return "Monkey Spirit";
            case 447: return "Bird Spirit";
            case 448: return "Ink Painting";
            case 449: return "Izana’s Scroll";

            //ALL MAGIC BOOKS - 15
            case 450: return "Empty Book";

            //MISCELLANEOUS - 14
            case 451: return "Dragonstone";
            case 452: return "Dragonstone+";
            case 453: return "Beaststone";
            case 454: return "Beastrune";
            case 455: return "Beaststone+";
            case 456: return "Broken Stone"; // - 15
            case 457: return "Draconic Rage";
            case 458: return "Dark Breath";
            case 459: return "Dragon Breath";
            case 460: return "Dragon Breath";
            case 461: return "Astral Breath";
            case 462: return "Blighted Claws";
            case 463: return "Blighted Talons";
            case 464: return "Expiration";
            case 465: return "Shackled Fist";
            case 466: return "Gauntlet";
            case 467: return "Rock";
            case 468: return "Massive Rock";
            case 469: return "Saw";
            case 470: return "Big Saw";

            //OTHER ITEMS - 15
            case 471: return "Life Ring";
            case 472: return "Elite Ring";
            case 473: return "Thief Ring";
            case 474: return "Prayer Ring";
            case 475: return "Pursuit Ring";
            case 476: return "Recover Ring";
            case 477: return "Bargain Ring";
            case 478: return "Knight Ring";
            case 479: return "Return Ring";
            case 480: return "Speed Ring";
            case 481: return "Magic Ring";
            case 482: return "Power Ring";
            case 483: return "Shield Ring";
            case 484: return "Barrier Ring";
            case 485: return "Leg Ring";
            case 486: return "Skill Ring";
            case 487: return "Circlet";
            case 488: return "Vulnerary";
            case 489: return "Concoction";
            case 490: return "Elixir";
            case 491: return "Pure Water";
            case 492: return "HP Tonic";
            case 493: return "Strength Tonic";
            case 494: return "Magic Tonic";
            case 495: return "Skill Tonic";
            case 496: return "Speed Tonic";
            case 497: return "Luck Tonic";
            case 498: return "Defence Tonic";
            case 499: return "Resistance Tonic";
            case 500: return "Door Key";
            case 501: return "Chest Key";
            case 502: return "Master Key";
            case 503: return "Seraph Robe";
            case 504: return "Energy Drop";
            case 505: return "Spirit Dust";
            case 506: return "Secret Book";
            case 507: return "Speedwing";
            case 508: return "Goddess Icon";
            case 509: return "Dracoshield";
            case 510: return "Talisman";
            case 511: return "Naga’s Tear";
            case 512: return "Boots";
            case 513: return "Arms Scroll";
            case 514: return "Master Seal";
            case 515: return "Second Seal";
            case 516: return "Bullion (S)";
            case 517: return "Bullion (M)";
            case 518: return "Bullion (L)";
            case 519: return "Sweet Tincture";
            case 520: return "Gaius’s Confect";
            case 521: return "Kris’s Confect";
            case 522: return "Tiki’s Tear";
            case 523: return "Seed of Trust";
            case 524: return "Reeking Box";
            case 525: return "Rift Door";
            case 526: return "Supreme Emblem";
            case 527: return "Dread Scroll";
            case 528: return "Wedding Bouquet";
            case 529: return "All Stats +2";
            case 530: return "Paragon";
            case 531: return "Iote’s Shield";
            case 532: return "Limit Breaker";
            case 533: return "Silver Card";
            case 534: return "Azura’s Salve";
            case 535: return "Gunter’s Potion";
            case 536: return "Asugi’s Confect";
            case 537: return "Rainbow Tonic";
            case 538: return "Allegro Harp";
            case 539: return "Shell Horn";
            case 540: return "Dragon Herbs";
            case 541: return "First Blood";
            case 542: return "Sighting Lens";
            case 543: return "Witch’s Mark"; //Need to change Third tier class names for witch/warlock
            case 544: return "Hero’s Brand";
            case 545: return "Exalt’s Brand";
            case 546: return "Fell Brand";
            case 547: return "Vanguard Brand";
            case 548: return "Armor Shield";
            case 549: return "Beast Shield";
            case 550: return "Point Blank";
            case 551: return "Bold Stance";
            case 552: return "Strengthtaker";
            case 553: return "Magictaker";
            case 554: return "Skilltaker";
            case 555: return "Speedtaker";
            case 556: return "Lucktaker";
            case 557: return "Defensetaker";
            case 558: return "Resistancetaker";
            case 559: return "Battle Seal";
            case 560: return "Visitation Seal";
            case 561: return "Master Emblem";
            case 562: return "Obstacle";
            case 563: return "Torch";
            case 564: return "Antidote";
            case 565: return "Member Card";
            case 566: return "Elite M";
            case 567: return "Charge M";
            case 568: return "Bargain M";
            case 569: return "Ambush M";
            case 570: return "Wrath M";
            case 571: return "Continue M";
            case 572: return "Prayer M";
            case 573: return "Awareness M";
            case 574: return "Sun Sword M"; //Sol M?
            case 575: return "Moonlight Sw M"; //Luna M?
            case 576: return "Odo Scroll";
            case 577: return "Baldo Scroll";
            case 578: return "Hezul Scroll";
            case 579: return "Dain Scroll";
            case 580: return "Noba Scroll";
            case 581: return "Neir Scroll";
            case 582: return "Ulir Scroll";
            case 583: return "Tordo Scroll";
            case 584: return "Fala Scroll";
            case 585: return "Sety Scroll";
            case 586: return "Blaggi Scroll";
            case 587: return "Heim Scroll";

            case 588: return "Full Blood Ring"; //Need better name
        }
        return "";
    }
}
